# -*- coding: utf-8 -*-
"""dash_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xdp6DhzVE0_d-WtLcGI1Khre_HJyPb4-
"""

import streamlit as st
import numpy as np
import pandas as pd

# Make sure evaluation_and_plots.py is in the SAME folder
from evaluation_and_plots import run_episode_with_metrics

st.set_page_config(page_title="AI Traffic Control Dashboard", layout="wide")
st.title("🚦 AI (RL+GNN) vs Fixed-Time – SUMO Dashboard")

st.sidebar.header("Simulation Controls")
max_steps = st.sidebar.slider("Simulation steps", 300, 3600, 900, step=300)

if "fixed_metrics" not in st.session_state:
    st.session_state["fixed_metrics"] = None
if "ai_metrics" not in st.session_state:
    st.session_state["ai_metrics"] = None

col_run1, col_run2 = st.columns(2)
with col_run1:
    if st.button("▶ Run Fixed-time episode"):
        st.session_state["fixed_metrics"] = run_episode_with_metrics("fixed", max_steps=max_steps)
with col_run2:
    if st.button("▶ Run AI episode"):
        st.session_state["ai_metrics"] = run_episode_with_metrics("ai", max_steps=max_steps)

st.markdown("---")

fixed_metrics = st.session_state["fixed_metrics"]
ai_metrics    = st.session_state["ai_metrics"]

if fixed_metrics and ai_metrics:
    fixed_wait_total = -fixed_metrics["episode_return"] * 1000.0
    ai_wait_total    = -ai_metrics["episode_return"]   * 1000.0
    improvement = (fixed_wait_total - ai_wait_total) / fixed_wait_total * 100

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("TLS count", fixed_metrics["num_tls"])
    c2.metric("Fixed total waiting index", f"{fixed_wait_total:,.0f}")
    c3.metric("AI total waiting index", f"{ai_wait_total:,.0f}")
    c4.metric("AI improvement", f"{improvement:.1f}%")

    fixed_wait = np.array(fixed_metrics["wait_trace"])
    ai_wait    = np.array(ai_metrics["wait_trace"])
    fixed_queue = np.array(fixed_metrics["queue_trace"])
    ai_queue    = np.array(ai_metrics["queue_trace"])
    fixed_proc  = np.array(fixed_metrics["processed_trace"])
    ai_proc     = np.array(ai_metrics["processed_trace"])

    steps = np.arange(len(fixed_wait))

    st.subheader("Wait time trend")
    df_wait = pd.DataFrame({
        "step": steps,
        "Fixed-time waiting": fixed_wait,
        "AI waiting": ai_wait,
    }).set_index("step")
    st.line_chart(df_wait)

    st.subheader("Queue vs processed vehicles")
    tab1, tab2 = st.tabs(["Fixed-time", "AI"])
    with tab1:
        df_fixed_qp = pd.DataFrame({
            "step": steps,
            "Queue": fixed_queue,
            "Processed": fixed_proc,
        }).set_index("step")
        st.line_chart(df_fixed_qp)
    with tab2:
        df_ai_qp = pd.DataFrame({
            "step": steps,
            "Queue": ai_queue,
            "Processed": ai_proc,
        }).set_index("step")
        st.line_chart(df_ai_qp)

    st.subheader("Intersection performance (avg per step)")
    fixed_stats = fixed_metrics["intersection_stats"]
    ai_stats    = ai_metrics["intersection_stats"]

    rows = []
    for tls_id in fixed_stats.keys():
        rows.append({
            "tls_id": tls_id,
            "Fixed avg wait":  fixed_stats[tls_id]["avg_wait"],
            "AI avg wait":     ai_stats[tls_id]["avg_wait"],
            "Fixed avg queue": fixed_stats[tls_id]["avg_queue"],
            "AI avg queue":    ai_stats[tls_id]["avg_queue"],
        })

    df_tls = pd.DataFrame(rows)
    st.dataframe(df_tls)

else:
    st.info("Run at least one Fixed-time and one AI episode to see the full dashboard.")